"""Add device_info to Customer

Revision ID: e62ec59b8ea7
Revises: e3cfb9b1011e
Create Date: 2025-10-24 11:47:02.015006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62ec59b8ea7'
down_revision = 'e3cfb9b1011e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_info', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('device_info')

    # ### end Alembic commands ###
